---
- name: Install Oracle Java
  hosts: webnx7
  vars:
    version: 8u171
    path_version: jre1.8.0_171
  tasks:
    - block:
      - copy:
          src: "files/jre-{{ version }}-linux-x64.rpm"
          dest: "/tmp/jre-{{ version }}-linux-x64.rpm"
      - block:
        - yum:
            name: "/tmp/jre-{{ version }}-linux-x64.rpm"
            state: present
        - alternatives:
            name: java
            path: "/usr/java/{{ path_version }}-amd64/bin/java"
        become: true
      - file:
          state: absent
          path: "/tmp/jre-{{ version }}-linux-x64.rpm"
      when: ansible_pkg_mgr == "yum"
    - block:
      - file:
          path: /usr/lib/jvm
          state: directory
      - unarchive:
          src: "files/jre-{{ version }}-linux-x64.tar.gz"
          dest: /usr/lib/jvm
      - alternatives:
          name: java
          path: "/usr/lib/jvm/{{ path_version }}/bin/java"
      become: true
      when: ansible_pkg_mgr == "apt"
