---
- name: Install StrongSwan VPN server
  hosts: "{{ hostname }}"
  become: true
  tasks:
  - apt:
      name: strongswan
      state: present
  - pip:
      name: letsencrypt-apache
  - command: certbot certonly --apache -d {{ vpn.domain_name }}
    args:
      creates: /etc/letsencrypt/live/{{ vpn.domain_name }}/cert.pem
  - name: Generate config
    template:
      src: ipsec.conf.j2
      dest: /etc/ipsec.conf
    tags:
      - config
  - name: Generate users
    template:
      src: ipsec.secrets.j2
      dest: /etc/ipsec.secrets
    tags:
      - auth
  - cron:
      minute: "0"
      hour: "0"
      job: "/usr/local/bin/certbot renew --quiet"
  - systemd:
      name: strongswan
      state: restarted
    tags:
      - config
  - iptables:
      chain: INPUT
      protocol: udp
      in_interface: "{{ ansible_default_ipv4.interface }}"
      to_ports: 500
      jump: ACCEPT
      comment: "IKEv2 ISAKMP"
  - iptables:
      chain: INPUT
      protocol: udp
      in_interface: "{{ ansible_default_ipv4.interface }}"
      to_ports: 4500
      jump: ACCEPT
      comment: "IKEv2 ESP"
  # https://wiki.strongswan.org/projects/strongswan/wiki/ForwardingAndSplitTunneling
  - sysctl:
      name: net.ipv4.ip_forward
      value: 1
      sysctl_set: yes
      state: present
      tags:
        - network
  - iptables:
      table: nat
      chain: POSTROUTING
      source: "{{ vpn.pool }}"
      jump: MASQUERADE
      comment: "masquerading"
    tags:
      - network
